### ISSUE TITLE
How you have trained the LID model

### ISSUE THREAD

**Issue by Durgesh92** [igorsitdikov/lid_kaldi#1]
Can you share your LID training recipe and data preparation guide?

**Comment by igorsitdikov** [comment]
Yes, sure. It's not a secret. I used https://github.com/kaldi-asr/kaldi/blob/master/egs/sre16/v2/run.sh. In `utt2spk` file I used `utt_id lang` instead of `utt_id speaker`

**Comment by Durgesh92** [comment]
Thanks, and to use the trained model with your vosk modified src what's the model structure? Can you please share your trained model to test?

**Comment by igorsitdikov** [comment]
You can find it here https://github.com/igorsitdikov/lid_kaldi/releases/tag/1.0.0

**Comment by Durgesh92** [comment]
Thanks for the quick response. Also, I have a question about training. How much data do you recommend for each language? also is it necessary to have an even distribution of data volume for each language?

**Comment by igorsitdikov** [comment]
https://arxiv.org/abs/2011.12998
