### ISSUE TITLE
How to use lid_kaldi 

### ISSUE THREAD

**Issue by asadullah73-ce** [igorsitdikov/lid_kaldi#2]
How to use lid_kaldi for language identification?

**Comment by igorsitdikov** [comment]
You can find example here https://github.com/igorsitdikov/lid_kaldi/blob/master/python/example/test_simple.py

**Comment by asadullah73-ce** [comment]
Where to get lid-model in the example.
I am getting this error in the example:
from lid import Model, KaldiRecognizer
ModuleNotFoundError: No module named 'lid'

**Comment by s-chizhik** [comment]
Hi! Thx @igorsitdikov for your work! I have related question.

I installed `whl` on my PC. But when I try to run example, I got an error 
```
ERROR ([5.5.873~1-75ec]:ReadConfigFile():parse-options.cc:462) Cannot open config file: lid-model/mfcc.conf
```

I suppose I need to get somewhere `lid-model` folder. Where I can get it?

**Comment by s-chizhik** [comment]
@asadullah73-ce install whl file for your platform from releases page.

For example
```
pip install https://github.com/igorsitdikov/lid_kaldi/releases/download/1.0.1/lid-1.0.1-py3-none-manylinux2010_x86_64.whl
```

**Comment by s-chizhik** [comment]
Ok, I figured out with my problem. I was misled because actual model was in version https://github.com/igorsitdikov/lid_kaldi/releases/tag/1.0.0 and actual whl in https://github.com/igorsitdikov/lid_kaldi/releases/tag/1.0.1

**Comment by igorsitdikov** [comment]
@s-chizhik , @asadullah73-ce updated release 1.0.1, added archive with the lid-model. https://github.com/igorsitdikov/lid_kaldi/releases/download/1.0.1/lid-model.tar.xz

**Comment by s-chizhik** [comment]
@igorsitdikov thx a lot!

**Comment by asadullah73-ce** [comment]
One more question please.
Does this detect other languages e.g Hindi or Urdu or Arabic?

**Comment by asadullah73-ce** [comment]
Okay, I was able to detect Urdu language from the code.
